language: go
go:
  - "1.10.x"
  - "1.11.x"
  - "1.12.5"
  - "1.12.x"
  - "1.13.x"
  - "1.x"
  - "master"

addons:
  apt:
    packages:
      - libldtl-dev

sudo: false

install:
  - go get -d -v -t ./...
script:
  - make
